# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KdGen < Formula
  desc "A Go code generator for enums."
  homepage "https://github.com/khuong02/kd-gen"
  version "0.2.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khuong02/kd-gen/releases/download/0.2.1/kd-gen_darwin_amd64.tar.gz"
      sha256 "21b7a41f0b26a0533b19957bdf43c678f21b87f80bb192f4feb2c6393902f104"

      def install
        bin.install "kd-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khuong02/kd-gen/releases/download/0.2.1/kd-gen_darwin_arm64.tar.gz"
      sha256 "d78ecb6a5e68a96f790b3f4ccea6902d3d2ce8a27534d37193715b4269a6751c"

      def install
        bin.install "kd-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/khuong02/kd-gen/releases/download/0.2.1/kd-gen_linux_amd64.tar.gz"
      sha256 "330978d6833def7cddd89e66f462e2ff7e95c4b1e52a04fff19df5457cfbefb8"
      def install
        bin.install "kd-gen"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/khuong02/kd-gen/releases/download/0.2.1/kd-gen_linux_arm64.tar.gz"
      sha256 "32c3ff04b3f2adc64a4428340520a9507c4e2254386e9e615a105de21ed48fd0"
      def install
        bin.install "kd-gen"
      end
    end
  end
end
