# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KdGen < Formula
  desc "A Go code generator for enums."
  homepage "https://github.com/khuong02/kd-gen"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khuong02/kd-gen/releases/download/v0.1.0/kd-gen_darwin_amd64.tar.gz"
      sha256 "88162544472bf3dc0681a7a425ffeb856085723320eaea16319dc8b03d5048de"

      def install
        bin.install "kd-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khuong02/kd-gen/releases/download/v0.1.0/kd-gen_darwin_arm64.tar.gz"
      sha256 "9fd531eb28c666962dd4675cf71bb229271f95ac3be4f509a816172fba33876e"

      def install
        bin.install "kd-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/khuong02/kd-gen/releases/download/v0.1.0/kd-gen_linux_amd64.tar.gz"
      sha256 "d2fbbffd5f8c8e4041e0d5e0f69f420e89aaed1838d516d31d0795baec66c2b7"
      def install
        bin.install "kd-gen"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/khuong02/kd-gen/releases/download/v0.1.0/kd-gen_linux_arm64.tar.gz"
      sha256 "8acdff5a5e80cca5eff87f4978ad6b91dbbe35548ba892fdd9d49726ad09fd20"
      def install
        bin.install "kd-gen"
      end
    end
  end
end
