# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class KdGen < Formula
  desc "A Go code generator for enums."
  homepage "https://github.com/khuong02/kd-gen"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/khuong02/kd-gen/releases/download/0.1.0/kd-gen_darwin_amd64.tar.gz"
      sha256 "2e300e2622c542652c53a9db78ee554d65b7660e2056f6a01a9c37400ad39dae"

      def install
        bin.install "kd-gen"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/khuong02/kd-gen/releases/download/0.1.0/kd-gen_darwin_arm64.tar.gz"
      sha256 "6424697b38bb420cc5afe515c3b3abc92c6bc9469dfb33e9454e337ed6f6bc3d"

      def install
        bin.install "kd-gen"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? and Hardware::CPU.is_64_bit?
      url "https://github.com/khuong02/kd-gen/releases/download/0.1.0/kd-gen_linux_amd64.tar.gz"
      sha256 "ef3e8d37125d1cf57718134450a02547414af7bb068c830d9c05ebb0a1863ba9"
      def install
        bin.install "kd-gen"
      end
    end
    if Hardware::CPU.arm? and Hardware::CPU.is_64_bit?
      url "https://github.com/khuong02/kd-gen/releases/download/0.1.0/kd-gen_linux_arm64.tar.gz"
      sha256 "4dbdd6a665aa3720880705caf363ccbb8c2d233e2043c98403b787494b0aec24"
      def install
        bin.install "kd-gen"
      end
    end
  end
end
